baseurl = "http://www.starprosper.com/"
languageCode = "en-us"
title = "Star Prosper"
# Enable comments by entering your Disqus shortname
disqusShortname = "starprosper"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per site
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[permalinks]
    # post = "/:year/:month/:day/:slug"
    post = "/:slug/:day/:month/:year"


[params]
    # Tell me who you are
    author = "Philip Stewart"
    bio = "90% Psychology 10% Trading"
    location = "Earth"
    site_description = ""
    copyright  = "Star Prosper"
    avatar = "css/images/avatar.png"

    # Format dates with Go's time formatting
    date_format = "22/01/2016"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

#[[params.menu]]
#    before = false
#    label  = "Tags"
#    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://www.tradingview.com/u/StarProsper/"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = "https://www.youtube.com/channel/UC4V9RRIXUMCHf5uNs0yKFuw"
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "http://facebook.com/starprosper"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "philipstarpros"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
